### PR TITLE
Skip rmoved images plus some fixup

### PR DESCRIPTION
**Pull request by nagos**
- Automaticly skip removed imgur images.
  Images compared to known dimensions, and skipped if matched.
- Fixed
- looping, when there is no more images.
- Preload next image from freshly loaded batch.
- Fixed GET request to /true url (incorrect usage of poster tag)

### CODE REVIEW

**Comment by ubershmekel** [comment]
Does imgur have an API where it defines whether the image is removed or not? `skip 161x81 images` seems a bit dangerous...

https://www.google.com/search?q=bla&biw=1920&bih=1075&tbm=isch&source=lnt&tbs=isz:ex,iszw:161,iszh:81#tbs=isz:ex%2Ciszw:161%2Ciszh:81&tbm=isch&q=a+OR+b+OR+d+OR+d

**Comment by nagos** [comment]
I can not see specific api. May be it will show some error code.
But either way, imgur api does not used for images right now, it would requre some rework.

I tried other ways, but failed to catch redirect to http://i.imgur.com/removed.png from browser.
My reasoning was - dimensions too specific, and image too small to skip legitimate image by mistake.

**Comment by nagos** [comment]
What about commit 406bc24? It does not depend on others in this pull request.

**Comment by ubershmekel** [comment]
`Fix behavior when there aren't more pictures` if that problem still exists - would be welcome on its own.

**Comment by dd-gamer** [comment]
Sometimes, when an image/video can't be loaded, the slideshow says stuck on that post. Maybe you could also add a general 'continuous' time to skip the broken/removed posts.

**Pull request closed without merging**
