### PR TITLE
Galleries

### PR DESCRIPTION
**Pull request by felixs-alt**
instead of just showing the first photo of a gallery it will go through all the photos in the gallery

### CODE REVIEW

**Comment by ROunofF** [comment]
Was literally coming to implement this. GJ :)

**Comment by ubershmekel** [comment]
Looking at https://deploy-preview-166--redditp.netlify.app/r/comics the UI can be a bit confusing with missing numbers. There probably should be an indicator that you're in a gallery. Right now the slide number gets highlighted only for the last panel.

**Comment by felixs-alt** [comment]
> Looking at https://deploy-preview-166--redditp.netlify.app/r/comics the UI can be a bit confusing with missing numbers. There probably should be an indicator that you're in a gallery. Right now the slide number gets highlighted only for the last panel.

I will probably update this soon with a little indicator showing what slide you are on and how many there are.

**Comment by omegasome** [comment]
This is fantastic, but it seems like navigation using the onscreen arrow button is borked, at least in firefox; if you load this branch and visit /r/pics or /r/food then the left arrow button works as intended, but the right arrow button just brings you back to image #1 no matter where you are.

Worse, it seems like if you use the onscreen right arrow button while nsfw is enabled, navigation is disabled completely—once you click it the arrow buttons, arrow keys, and number buttons all become nonfunctional, even if there are no NSFW posts in sight.

Will attempt to untangle this.

**Comment by QuantumManiac** [comment]
Any plans to push this PR through the finish line? I was planning on implementing this myself, until I found this PR, and would be happy to have the torch passed to me to try to finish up.

**Comment by felixs-alt** [comment]
Merged two pullrequests @omegasome made.
Thank You, @omegasome.

**Comment by QuantumManiac** [comment]
I noticed that the 'g' key is set to skip a gallery. Is there a way to do so on mobile and/or with the mouse, e.g. with a button or something?

**Comment by ubershmekel** [comment]
@felixs-alt can you remove the change to the CNAME file? I could merge it then.

**Pull request merged**
