### PR TITLE
Overlay

### PR DESCRIPTION
**Pull request by JohnnyDarks**
OK, shuffled things around to move the play button on top.

### CODE REVIEW

**Comment by JohnnyDarks** [comment]
@TimotheeMalard Thanks for the catch. This should fix it. If it gets accepted, let me know if there are any other problems.

**Comment by ubershmekel** [comment]
@JohnnyDarks where did @TimotheeMalard say what?

**Comment by JohnnyDarks** [comment]
[here](https://github.com/ubershmekel/redditp/pull/139#issuecomment-1124330529).

**Comment by ubershmekel** [comment]
Thanks.

**Pull request merged**
