### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by MrHant**
linting html and JS
no functionality changes

### CODE REVIEW

**Comment by ubershmekel** [comment]
About the HTML - I think closers are important for simplicity of parsing. I.e. there should never be an opener without a closer even if it's allowed by HTML standards. E.g. I don't want to accidentally start searching for the closing `</input>` in case I forget `<input>` is allowed by itself. Not to mention the list of void element tags may change.

There are a few more outstanding html validation issues too:

https://validator.w3.org/nu/?doc=http%3A%2F%2Fredditp.com%2F

The `js` semicolons seem reasonable though I don't think I can merge just one file.

**Comment by MrHant** [comment]
List of void tags is a part of html specification, so it's not supposed to change frequently. Browsers are trying to work according to specification, so I guess it's a good practice to follow all the guidelines.

Which exact not fixed outstanding errors do you mean?

All the errors displayed for me are fixed in commit f12e6d6

"Error: Bad value true for attribute checked on element input."
is fixed by leaving just "checked" instead of "checked=true"

**Comment by ubershmekel** [comment]
According to this http://stackoverflow.com/questions/23739270/image-tag-closing/23739417#23739417 the ending `/` on void elements is allowed according to the spec and I prefer having it there.

**Comment by MrHant** [comment]
Please see void elements updated.

**Comment by ubershmekel** [comment]
Thank you for doing this!

**Pull request merged**
