### PR TITLE
Fix dashboard display

### PR DESCRIPTION
**Pull request by d33tah**
I was getting failed requests for the dashboard. This patch changes them to code that triggers CORS protection errors, but perhaps just because I wasn't testing with SSL?

### CODE REVIEW

**Comment by d33tah** [comment]
@ubershmekel could you try this one out and see if it fixes logged-in dashboard display for you?

**Comment by ubershmekel** [comment]
Sorry this took me forever to notice.

I'm confused. What is the problem? Can you share a link that's broken?

**Comment by d33tah** [comment]
@ubershmekel Quite frankly I don't recall anymore - judging by my previous comments, it looks like the patch should make it possible to see one's logged-in default dashboard. Does it still do that?

**Comment by ubershmekel** [comment]
Gotcha. I'll close for now. If the issue arises - we'll revisit.

Again, I apologize it took me so long to get to this, and thank you for the PR. Feel free to re-open if you reproduce the issue.

**Pull request closed without merging**
