### PR TITLE
sound toggle and window title from post title

### PR DESCRIPTION
**Pull request by smarek**
easy changes

### CODE REVIEW

**Comment by ubershmekel** [comment]
Both this and https://github.com/ubershmekel/redditp/pull/109 look to be the same changes, no?

**Comment by smarek** [comment]
Yes, those are same changes, I actually forgot about opening the #109 
Anyway, here it's in 2 commits, #109 is 5 commits for some reason, if you merge with squashing commits together, it'll make no difference. Merge the one you like, the other one can be closed without merging :)

**Comment by ubershmekel** [comment]
Thank you @smarek

**Comment by smarek** [comment]
you're welcome

**Pull request closed without merging**
