### PR TITLE
Fix for sound

### PR DESCRIPTION
**Pull request by MrSpiffyClean**
Possible fix to #123.

(I apologize for the commit history, I think I didn't rebase when resyncing my fork)

### CODE REVIEW

**Comment by ubershmekel** [comment]
Looking at https://deploy-preview-128--redditp.netlify.app/r/nextfuckinglevel/comments/m86auw/taking_on_physical_rehab_1_step_at_a_time/ it doesn't seem that this change makes audio work.

**Comment by MrSpiffyClean** [comment]
Did you remember to check the sound checkbox on the lower left panel?

**Comment by ubershmekel** [comment]
Strange. I definitely did then. And now when I went to look at the link - the sound was not working, I clicked the sound checkbox, still no sound. I refreshed after setting the sound to on, then it did work. Now it works no matter how the checkbox is initially. The issue might be something that was cached in my system somehow.

Thank you so much @MrSpiffyClean !

**Comment by MrSpiffyClean** [comment]
There might be some syncing issues with the video and audio being retrieved at different times, but after a repeat stuff seems to sort itself out.

**Pull request merged**
