### PR TITLE
Added history / back button support.

### PR DESCRIPTION
**Pull request by murgo**
I implemented back button and history support just for kicks (as discussed on #77). Feel free to merge it or not at your own pleasure.

I tried to break it but it seems to work pretty ok. There is a small 1 item queue for animations, so when you frantically hit back button many times you end up on the same pic you're supposed to even with animations running.

There are some edge cases like going to the slideshow, then going a lot of images further, then going via a link to external site and returning to redditp via back (so the image is no longer loaded or the image with the same index might be wrong), but these cases should just throw you to the start of the slideshow as before.

I suggest you give it a spin, for me it increases usability dramatically.

### CODE REVIEW

**Comment by murgo** [comment]
This might need some additional checks and safeguards for IE <10.

**Comment by ubershmekel** [comment]
Thank you for implementing this @murgo - I'll try and look at it during the next week.

**Comment by murgo** [comment]
I added some checks to make sure everything should work even if some browser didn't have history api defined.

**Comment by ubershmekel** [comment]
I finally got to that weekend. Seriously though, thank you for this work. I like it, I feel bad it took so long, and have merged it in.

I wish redditp was structured better, with defined boundaries for the different parts. Specifically I feel bad that the `History / back button stuff` comment is just a section, and right now it isn't clera why `scheduledAnimation` and `rp.session.isAnimating` are both needed. I'll get to clean ups some day.

**Pull request merged**
