### PR TITLE
Temporary fix while Gfycat cajax is down

### PR DESCRIPTION
**Pull request by half-cambodian-hacker-man**
At the moment, all gfycat fetches are failing. I think it's because gfycat have removed their AJAX api at /get/cajax/

### CODE REVIEW

**Comment by ubershmekel** [comment]
Thank you @half-cambodian-hacker-man for this! I didn't even know there was a problem. I just pushed this fix to live.

There is still a problem with e.g. https://giant.gfycat.com/baggygargantuanharvestmen.webm not working but https://giant.gfycat.com/BaggyGargantuanHarvestmen.webm does. I wonder how reddit does it here: https://www.reddit.com/r/whitepeoplegifs/comments/a0n0jj/the_best_way_to_celebrate_after_landing_on_mars/

I won't have time to figure this out soon so if you do it would be much appreciated.

**Comment by Hrxn** [comment]
It should be back up right now..?

**Comment by ubershmekel** [comment]
I didn't realize it was an outage. I thought it was a deprecation. I've reverted this. Again, thank you!

**Comment by ubershmekel** [comment]
I guess the ideal solution would be to try cajax then fallback to guessing the URL if it fails.

**Pull request merged**
